default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: rails
  password: railspass
  host: localhost
  socket: /tmp/mysql.sock
  
development:
  <<: *default
  database: intergrow_development

test:
  <<: *default
  database: intergrow_test

production:
  <<: *default
  database: intergrow_production
  username: intergrow
  password: <%= ENV['intergrow_PASSWORD'] %>
